Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Text;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using ProjectForHealing.Models;
using ProjectForHealing.ViewModels;

namespace ProjectForHealing.Controllers
{
    public class AdminController : Controller
    {

        private CRMSContext context;
        private readonly IWebHostEnvironment hostingEnvironment;
        public AdminController(CRMSContext dbContext, IWebHostEnvironment hostingEnvironment)
        {
            this.hostingEnvironment = hostingEnvironment;
            context = dbContext;
        }
        
        //checks if logged in before being able to interact with any function in this controller
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            HttpContext.Session.TryGetValue("username", out var bytes);
            if (bytes == null)
            {
                context.Result = new RedirectResult("/");
                return;
            }
            var username = Encoding.UTF8.GetString(bytes);

            if (string.IsNullOrWhiteSpace(username))
            {
                context.Result = new RedirectResult("/");
                return;
            }

            
            base.OnActionExecuting(context);
        }
        public IActionResult Index()
        {
           ViewBag.name = HttpContext.Session.GetString("fname") + " " + HttpContext.Session.GetString("lname");
           ViewBag.email = HttpContext.Session.GetString("email");
            ViewBag.number = HttpContext.Session.GetString("pnumber");
            ViewBag.role = HttpContext.Session.GetString("role");
          
           
            return View();
        }
        public IActionResult AddAdmin()
        {
            return View();
        }
        

        [HttpPost]
        [Route("/Admin/AddAdmin")]
        public IActionResult AddAccount(AdminViewModel model)
        {
        
            if (ModelState.IsValid)
            {
               //if the actual file is not null
                
                Admin newAdmin = new Admin
                {
                    //  ResourceID = addEditorViewModel.ResourceID,
                    UserName = model.UserName,
                    Fname = model.Fname,
                    Lname = model.Lname,
                    Email = model.Email,
                    Pnumber = model.Pnumber,
                    AdminPassWord = model.AdminPassWord,
                    SuperUser = model.isAdmin,
                };
                context.Admin.Add(newAdmin);
                context.SaveChanges();
                return Redirect("/Admin/Created");
            }
            else
            {
                return View(model);
            }

        }
        public IActionResult Created()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            // todo: add validation for editing a resource
            var source = context.Resource.SingleOrDefault(x => x.ResourceID == id);
            return View(source);
        }
        [HttpPost]
        public IActionResult Edit(Resource source)
        {
            if (ModelState.IsValid)
            {
                if (Request.Form["ResourceTypes"].ToArray().Length == 1)
                {
                    source.RType1 = Request.Form["ResourceTypes"][0];

                }

                else if (Request.Form["ResourceTypes"].ToArray().Length == 2)
                {
                    source.RType1 = Request.Form["ResourceTypes"][0];
                    source.RType2 = Request.Form["ResourceTypes"][1];
                }
                else if (Request.Form["ResourceTypes"].ToArray().Length == 3)
                {
                    source.RType1 = Request.Form["ResourceTypes"][0];
                    source.RType2 = Request.Form["ResourceTypes"][1];
                    source.RType3 = Request.Form["ResourceTypes"][2];
                }
                else
                {

                }
                    

                context.Entry(source).State = EntityState.Modified;
                context.SaveChanges();
                ViewBag.Title = "Changes Saved";
                return View(source);
            }
            ViewBag.Title = "Changes not saved";
            return View(source);
        }
        public IActionResult ResourceManage()
        {

         
            var model = new ManageViewModel();
            model.resources = context.Resource.ToList();
            model.unassocResources = context.UnassocResource.ToList();

            return View(model);
        }

        [HttpGet]
        public IActionResult Unapproved() {

            List<Resource> resources = context.Resource.Where(x => x.IsApproved == false).ToList();
            return View(resources);
            
            
        }


       
        public IActionResult AdminList()
        {
            var admins = context.Admin;
        
            return View(admins);
        }



        [HttpGet]
        public IActionResult RemoveAdmin(string UserName)
        {

            Admin admin = context.Admin.SingleOrDefault(x => x.UserName == UserName);
            context.Admin.Remove(admin);

            context.SaveChanges();
            return Redirect("/Admin");
        }

        [HttpGet]
        public IActionResult Remove(int id)
        {

            Resource theResource = context.Resource.SingleOrDefault(x => x.ResourceID == id);
            context.Resource.Remove(theResource);
       string files = Path.Combine(hostingEnvironment.WebRootPath, "ResourceFiles/");

            FileInfo file = new FileInfo(files + theResource.PhotoPath);

            if (file.Exists)
            {
                file.Delete();
            }
            context.SaveChanges();
            return Redirect("/Admin/ResourceManage");
        }


        [HttpGet]
        public IActionResult Approve(int id )
        {
          
            Resource theResource = context.Resource.SingleOrDefault(x => x.ResourceID == id);
            theResource.IsApproved = true;
            sendEmail(theResource.OrgEmail);
            
            context.SaveChanges();
            return Redirect("/Admin/ResourceManage");
        }
/*
           [HttpGet]
        public IActionResult ViewSource(int id)
        {
            var source = context.Resource.SingleOrDefault(x => x.ResourceID == id);
            return View(source);
        }
        */
        public IActionResult AddUnassocResource()
        {
            UnassocViewModel rec = new UnassocViewModel();
            return View(rec);
        }

        [HttpPost]
        [Route("/Admin/AddUnassocResource")]
        public IActionResult AddUnassocResource(UnassocViewModel model)
        {


            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
               
                //if the actual file is not null
                if (model.UploadedFile != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "ResourceFiles");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.UploadedFile.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    model.UploadedFile.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                UnassocResource newRec = new UnassocResource
                {
                    //  ResourceID = addEditorViewModel.ResourceID,
                    Name = model.Name,
                   Description = model.Description,
                    FilePath = uniqueFileName
                };
                context.UnassocResource.Add(newRec);
                context.SaveChanges();
                return Redirect("/Resource/Submitted");
            }
            else
            {
                return View(model);
            }
        }

        public IActionResult UnassocResourceList()
        {
            var rec = context.UnassocResource.ToList();
            return View(rec);
        }

        public IActionResult DelUnassocResource(int id )
        {
            var education = context.UnassocResource.SingleOrDefault(x => x.ID == id);
            context.UnassocResource.Remove(education);
            if (education.FilePath != null)
            {
                string files = Path.Combine(hostingEnvironment.WebRootPath, "ResourceFiles/");
                FileInfo file = new FileInfo(files + education.FilePath);
                if (file.Exists)
                {
                    file.Delete();
                }

            }
        



            context.SaveChanges();
            return Redirect("/Home/UnassocResources");
            
        }

        public void sendEmail(string email)
        {

            MailMessage mail = new MailMessage();
            SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com");
            mail.From = new MailAddress("chingchong@gmail.com");
            mail.To.Add(email);
            mail.Subject = "Approval Test Email";
            mail.Body = "This is a test email from Neighborly.org to verify that your email has been submitted ";


            SmtpServer.Port = 587;
            SmtpServer.Credentials = new System.Net.NetworkCredential("abc031998@gmail.com", "Xrtfvptbpzmq1308dizz1");
            SmtpServer.EnableSsl = true;

            SmtpServer.Send(mail);

        }


    }
}

Controllers/ResourceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ProjectForHealing.Models;
using ProjectForHealing.ViewModels;

namespace ProjectForHealing.Controllers
{
    public class ResourceController : Controller
    {
        private CRMSContext context;
        private readonly IWebHostEnvironment hostingEnvironment;
        //asking to get instance of CRMS context
        private String emailAdd;
        public ResourceController(CRMSContext dbContext, IWebHostEnvironment hostingEnvironment)
        {
            context = dbContext;
            this.hostingEnvironment = hostingEnvironment;
        }


        public IActionResult Submitted()
        {

            sendEmail();
            return View();
        }

        public IActionResult Add()
        {
            AddResourceViewModel addResourceViewModel = new AddResourceViewModel();
            return View(addResourceViewModel);
        }
   

        [HttpPost]
        [Route("/Resource/Add")]
        public IActionResult Add(AddResourceViewModel addResourceViewModel)
        {

        
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                //if the actual file is not null

                


                if(addResourceViewModel.UploadedFile != null)
                {
                  string uploadsFolder =  Path.Combine(hostingEnvironment.WebRootPath, "ResourceFiles");
                  uniqueFileName = Guid.NewGuid().ToString() + "_" + addResourceViewModel.UploadedFile.FileName;
                   string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    addResourceViewModel.UploadedFile.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                string[] holding = new string[3];
                int i = 0;
               while(i < addResourceViewModel.ResourceTypes.Length)
                {
                    holding[i] = addResourceViewModel.ResourceTypes[i];
                    i++;
                }
                Resource newResource = new Resource
                {
                    //  ResourceID = addResourceViewModel.ResourceID,
                    OrgName = addResourceViewModel.OrgName,
                    OrgNumber = addResourceViewModel.OrgNumber,
                    OrgEmail = addResourceViewModel.OrgEmail,
                    OrgAddress = addResourceViewModel.OrgAddress,
                    OrgZip = addResourceViewModel.OrgZip,
                    OrgSte = addResourceViewModel.OrgSte,
                    OrgDescription = addResourceViewModel.OrgDescription,
                    WebsiteUrl = addResourceViewModel.WebsiteUrl,
                    PhotoPath = uniqueFileName,
                    IsApproved = addResourceViewModel.IsApproved,
                    RType1 = holding[0],

                    RType2 = holding[1],

                    RType3 = holding[2],
                    lat = addResourceViewModel.lat,
                    lng = addResourceViewModel.lng,
                    Tag1 = addResourceViewModel.Tag1,
                    Tag2 = addResourceViewModel.Tag2,
                    Tag3 = addResourceViewModel.Tag3,
                    Tag4 = addResourceViewModel.Tag4,
                    Tag5 = addResourceViewModel.Tag5


                };
                context.Resource.Add(newResource);
                context.SaveChanges();
                emailAdd = newResource.OrgEmail;
                return Redirect("/Resource/Submitted");
            }
            else
            {
                return View(addResourceViewModel);
            }
            
        }


        public void sendEmail()
        {

            MailMessage mail = new MailMessage();
            SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com");
            mail.From = new MailAddress("chingchong@gmail.com");
            mail.To.Add("abc03199@gmail.com");
            mail.Subject = "Submission Test Email";
            mail.Body = "This is a test email from Neighborly.org ";


            SmtpServer.Port = 587;
            SmtpServer.Credentials = new System.Net.NetworkCredential("abc031998@gmail.com", "Xrtfvptbpzmq1308dizz1");
            SmtpServer.EnableSsl = true;

            SmtpServer.Send(mail);

        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project For Healing</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://kit.fontawesome.com/2004ec8e2c.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="~/js/map-font-icons.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">

    <style>

        .map-icon-label i {
            font-size: 24px;
            color: #FFFFFF;
            line-height: 55px;
            text-align: center;
            white-space: nowrap;
        }
    </style>
    <script src="https://kit.fontawesome.com/2004ec8e2c.js" crossorigin="anonymous"></script>

    <style>

        #legend {
            font-family: Arial, sans-serif;
            background: #fff;
            padding: 10px;
            margin: 10px;
            border: 3px solid #000;
        }

        body {
            position: relative;
            overflow: scroll;
            min-height: 100%;
            margin: 0px;
            padding: 0px;
        }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/Neighborly-logo.png " alt="Project For Healing" style="width:150px;height:75px;"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home<span class="sr-only">(current)</span></a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Resource" asp-action="Add">Your Service</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="UnassocResourceIndex">Additional Resources</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            @if (Context.Session.GetString("username") == null)
                            {
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Login"></a>
                            }
                            else
                            {


                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">CRMS Dashboard</a>
                                <div class="dropdown-menu" style="">
                                    <a class="dropdown-item" href="/Admin/Index">Dashboard</a>
                                    <a class="dropdown-item" href="/Admin/ResourceManage">Manage Resources</a>
                                    <a class="dropdown-item" href="/Home/Logout">Logout</a>

                                    @if (Context.Session.GetString("role") == "Master Admin")
                                    {<div class="dropdown-divider"></div>

                                        <a class="dropdown-item" href="/Admin/AddAdmin">Create New Admin</a>
                                        <a class="dropdown-item" href="/Admin/AdminList">Remove Admin</a>


                                    }

                                </div>

                            </li>
                        }


                        </ul>
                        <form class="form-inline my-2 my-lg-0" asp-controller="Home" asp-action="Search">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search" name="search">
                            <button class="btn btn-secondary border rounded my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </nav>
        </header>
        <!--  <div class="container middlebody">-->
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <!-- </div>-->
        
        <footer class="border-top footer text-muted">
            <div class="container" style="max-height:15px">
                &copy;2019-2020 WeaveTales. All Rights Reserved - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> -    @if (Context.Session.GetString("username") == null)
                {
                    <a asp-area="" asp-controller="Home" asp-action="Login">Admin Login</a>
                }
                else
                {
                    <a asp-area="" asp-controller="Admin" asp-action="Index">Dashboard</a>
                }
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)



    </body>
</html>